### ISSUE TITLE
Not compatible with wnj bookmarklet

### ISSUE THREAD

**Issue by alopatindev** [penpenpng/nip07-awaiter#1]
Can we make it compatible with [wnj](https://github.com/fiatjaf/window.nostr.js#bookmarklet) bookmarklet? It allows to sign messages using external signer via bunker URI.

It works for me only with `configurable: true`, otherwise it throws `TypeError: Cannot redefine property: nostr`. I used [Amber](https://github.com/greenart7c3/Amber) as signer.

**Comment by penpenpng** [comment]
It seems to me that there is no perfect way to fix this problem. Primitive polling would be the only compromise. I will try to fix as much as I can in the coming days.
